//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentifyx.Users.Exceptions.MessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserValidatorErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserValidatorErrorMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentifyx.Users.Exceptions.MessageResource.UserValidatorErrorMessageResource", typeof(UserValidatorErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be at most 100 characters long..
        /// </summary>
        public static string CITY_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CITY_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement must be at most 200 characters long..
        /// </summary>
        public static string COMPLEMENT_MAX_LENGTH {
            get {
                return ResourceManager.GetString("COMPLEMENT_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must be 11 or 14 digits..
        /// </summary>
        public static string DOCUMENT_LENGTH {
            get {
                return ResourceManager.GetString("DOCUMENT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string EMPTY_CITY {
            get {
                return ResourceManager.GetString("EMPTY_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is required..
        /// </summary>
        public static string EMPTY_DOCUMENT {
            get {
                return ResourceManager.GetString("EMPTY_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string EMPTY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood is required..
        /// </summary>
        public static string EMPTY_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("EMPTY_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required..
        /// </summary>
        public static string EMPTY_NUMBER {
            get {
                return ResourceManager.GetString("EMPTY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required..
        /// </summary>
        public static string EMPTY_STATE {
            get {
                return ResourceManager.GetString("EMPTY_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required..
        /// </summary>
        public static string EMPTY_STREET {
            get {
                return ResourceManager.GetString("EMPTY_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode is required..
        /// </summary>
        public static string EMPTY_ZIPCODE {
            get {
                return ResourceManager.GetString("EMPTY_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be a valid email address..
        /// </summary>
        public static string INVALID_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be at most 100 characters long..
        /// </summary>
        public static string INVALID_EMAIL_LENGTH {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at most 30 characters long..
        /// </summary>
        public static string NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 7 characters long..
        /// </summary>
        public static string NAME_MIN_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood must be at most 100 characters long..
        /// </summary>
        public static string NEIGHBORHOOD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be at most 10 characters long..
        /// </summary>
        public static string NUMBER_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NUMBER_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must be 2 characters (UF)..
        /// </summary>
        public static string STATE_LENGTH {
            get {
                return ResourceManager.GetString("STATE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street must be at most 200 characters long..
        /// </summary>
        public static string STREET_MAX_LENGTH {
            get {
                return ResourceManager.GetString("STREET_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode must be 8 digits..
        /// </summary>
        public static string ZIPCODE_LENGTH {
            get {
                return ResourceManager.GetString("ZIPCODE_LENGTH", resourceCulture);
            }
        }
    }
}
